/**
 * @file Interfaces - ParsedPath
 * @module pathe/interfaces/ParsedPath
 */

import type { ExactOptionalPropertyTypes } from '@flex-development/tutils'
import type PathObject from './path-object'

/**
 * Object representing significant elements of a path.
 *
 * This object can be generated by [`parse`][1] or consumed by [`format`][2].
 *
 * [1]: {@link ../lib/parse.ts}
 * [2]: {@link ../lib/format.ts}
 * [3]: {@link ./path-object.ts}
 *
 * @see [`PathObject`][3]
 *
 * @extends {ExactOptionalPropertyTypes<Required<PathObject>>}
 */
interface ParsedPath extends ExactOptionalPropertyTypes<Required<PathObject>> {}

export type { ParsedPath as default }
